"""Persistent storage for Smart Home security, sensor and energy events.

Storage backend:
- PostgreSQL/Neon when DATABASE_URL is configured.
- SQLite as the local-development fallback.

The rest of the application uses the same small database API regardless of the
backend. CCTV images/videos are never stored in the database; only their
reference/path is persisted in ``snapshot_path``.
"""

from pathlib import Path
import json
import os
import sqlite3
import threading
import time

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # dotenv is optional at import time; Render supplies environment variables directly.
    pass

from datetime import datetime, timezone, timedelta

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "data" / "smarthome.db"


def _database_url():
    """Return the current PostgreSQL URL, if one is configured."""
    url = os.getenv("DATABASE_URL", "").strip()
    if url.startswith(("postgres://", "postgresql://")):
        return url
    return None


def _use_postgres():
    """Use PostgreSQL only when DATABASE_URL is explicitly configured."""
    return _database_url() is not None


class _PooledPg:
    """A reusable PostgreSQL connection that behaves like the old one-shot
    ``with _connect() as conn`` object, but is NOT closed on exit.

    Opening a brand-new TLS connection to a remote database (Neon) costs
    hundreds of milliseconds, and the app used to do it for every single
    read. A small pool removes that cost from every page load and button press.
    """
    _idle = []                                   # connections ready for reuse
    _lock = threading.Lock()
    _slots = threading.BoundedSemaphore(8)       # never hold more than 8 connections

    def __init__(self):
        _PooledPg._slots.acquire()
        self._conn = None
        try:
            with _PooledPg._lock:
                self._conn = _PooledPg._idle.pop() if _PooledPg._idle else None
            if self._conn is not None:
                try:
                    if self._conn.closed or self._conn.broken:
                        raise RuntimeError("stale")
                    if time.monotonic() - getattr(self._conn, "_last_used", 0) > 20:
                        self._conn.execute("SELECT 1")      # cheap liveness check after idle
                        self._conn.rollback()
                except Exception:
                    self._discard()
            if self._conn is None:
                import psycopg
                from psycopg.rows import dict_row
                # Neon accepts the SSL parameters contained in its connection string.
                self._conn = psycopg.connect(_database_url(), row_factory=dict_row,
                                             connect_timeout=10)
        except Exception:
            _PooledPg._slots.release()
            raise

    def _discard(self):
        try:
            self._conn.close()
        except Exception:
            pass
        self._conn = None

    def __getattr__(self, name):
        return getattr(self._conn, name)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self._conn.commit()
            else:
                self._conn.rollback()
            self._conn._last_used = time.monotonic()
            with _PooledPg._lock:
                _PooledPg._idle.append(self._conn)
        except Exception:
            self._discard()
        finally:
            _PooledPg._slots.release()
        return False


def _connect():
    """Open a connection to the configured database backend."""
    if _use_postgres():
        try:
            import psycopg  # noqa: F401
        except ImportError as exc:
            raise RuntimeError(
                "DATABASE_URL is configured, but the PostgreSQL driver is not "
                "installed. Install the dependencies from requirements.txt."
            ) from exc
        return _PooledPg()

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _execute_schema(conn):
    """Create the common schema on either SQLite or PostgreSQL."""
    if _use_postgres():
        statements = [
            """
            CREATE TABLE IF NOT EXISTS events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL,
                event_type TEXT NOT NULL,
                severity TEXT NOT NULL DEFAULT 'info',
                source TEXT NOT NULL,
                location TEXT,
                message TEXT NOT NULL,
                snapshot_path TEXT,
                metadata TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type)",
            "CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity)",
            "CREATE INDEX IF NOT EXISTS idx_events_retention ON events(severity, created_at)",
            """
            CREATE TABLE IF NOT EXISTS runtime_state (
                id INTEGER PRIMARY KEY,
                updated_at TEXT NOT NULL,
                state_json TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS state_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL,
                state_json TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_state_history_created_at ON state_history(created_at)",
        ]
    else:
        statements = [
            """
            CREATE TABLE IF NOT EXISTS events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                event_type TEXT NOT NULL,
                severity TEXT NOT NULL DEFAULT 'info',
                source TEXT NOT NULL,
                location TEXT,
                message TEXT NOT NULL,
                snapshot_path TEXT,
                metadata TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type)",
            "CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity)",
            "CREATE INDEX IF NOT EXISTS idx_events_retention ON events(severity, created_at)",
            """
            CREATE TABLE IF NOT EXISTS runtime_state (
                id INTEGER PRIMARY KEY,
                updated_at TEXT NOT NULL,
                state_json TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS state_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                state_json TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_state_history_created_at ON state_history(created_at)",
        ]

    for statement in statements:
        conn.execute(statement)


_schema_ready = set()
_schema_lock = threading.Lock()


def init_db():
    """Create the database schema if it does not already exist.

    Runs the schema statements once per database per process. It used to run
    on EVERY query (a connection plus about ten CREATE statements each time),
    which made every page load and button press slow on a remote database.
    """
    key = (_database_url() or str(DB_PATH))
    if key in _schema_ready and (_database_url() or DB_PATH.exists()):
        return
    with _schema_lock:
        if key in _schema_ready and (_database_url() or DB_PATH.exists()):
            return
        with _connect() as conn:
            _execute_schema(conn)
            conn.commit()
        _schema_ready.add(key)


def get_latest_event_id():
    """Cheap 'did anything new get logged?' check used by the live push."""
    init_db()
    with _connect() as conn:
        row = conn.execute("SELECT MAX(id) AS m FROM events").fetchone()
    if not row:
        return 0
    value = row["m"] if isinstance(row, dict) or hasattr(row, "keys") else row[0]
    return int(value or 0)


def utc_now():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _placeholder():
    return "%s" if _use_postgres() else "?"


def log_event(event_type, severity, source, location, message,
              snapshot_path=None, metadata=None):
    """Persist an event and return its database ID."""
    init_db()
    p = _placeholder()
    sql = f"""INSERT INTO events
               (created_at,event_type,severity,source,location,message,snapshot_path,metadata)
               VALUES ({p},{p},{p},{p},{p},{p},{p},{p})"""
    values = (
        utc_now(), event_type, severity, source, location, message,
        snapshot_path,
        json.dumps(metadata or {}, ensure_ascii=False),
    )

    with _connect() as conn:
        if _use_postgres():
            row = conn.execute(sql + " RETURNING id", values).fetchone()
            conn.commit()
            return row["id"]
        cur = conn.execute(sql, values)
        conn.commit()
        return cur.lastrowid


def save_runtime_state(state):
    """Persist the latest live dashboard state as a single shared row.

    This is deliberately not historical storage: repeated sensor updates replace
    the same row, so live state can be shared between Render services without
    filling the incident history table.

    NOTE: this replaces the row unconditionally with whatever `state` the
    caller passes in. It is only safe to use when the caller just did its
    own read-modify-write and wants a plain "write this" - for merging a
    partial update onto whatever is CURRENTLY in the shared row (the
    common case), use update_runtime_state() below instead, which is
    race-safe against other processes/threads writing at the same time.
    """
    init_db()
    p = _placeholder()
    payload = json.dumps(state, ensure_ascii=False)
    with _connect() as conn:
        if _use_postgres():
            conn.execute(
                f"""INSERT INTO runtime_state(id, updated_at, state_json)
                    VALUES(1, {p}, {p})
                    ON CONFLICT (id) DO UPDATE SET
                        updated_at = EXCLUDED.updated_at,
                        state_json = EXCLUDED.state_json""",
                (utc_now(), payload),
            )
        else:
            conn.execute(
                f"""INSERT INTO runtime_state(id, updated_at, state_json)
                    VALUES(1, {p}, {p})
                    ON CONFLICT(id) DO UPDATE SET
                        updated_at=excluded.updated_at,
                        state_json=excluded.state_json""",
                (utc_now(), payload),
            )
        conn.commit()


def update_runtime_state(mutator):
    """Atomically read-modify-write the shared runtime_state row.

    `mutator(current_dict) -> new_dict` computes the new full state from
    whatever is CURRENTLY in the shared row. The read and the write happen
    inside one locked transaction, so a concurrent caller (a different
    thread in the same process, or a completely different process such as
    the web service vs. the background worker) cannot read the same old
    value, write in between, and have this call silently overwrite that
    other write with stale data - the classic problem with doing a plain
    "read, then separately write" as two independent database calls.

    - PostgreSQL: SELECT ... FOR UPDATE takes a row lock that blocks any
      other transaction from reading-for-update the same row until this
      one commits.
    - SQLite: BEGIN IMMEDIATE takes the write lock at the very start of
      the transaction (before even the SELECT), so no other connection
      can begin its own write transaction until this one commits - the
      equivalent guarantee for a single-row table in a single file.

    Returns the new merged state.
    """
    init_db()
    p = _placeholder()
    with _connect() as conn:
        if _use_postgres():
            row = conn.execute(
                "SELECT state_json FROM runtime_state WHERE id=1 FOR UPDATE"
            ).fetchone()
        else:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(
                "SELECT state_json FROM runtime_state WHERE id=1"
            ).fetchone()

        current = {}
        if row:
            raw = row["state_json"] if isinstance(row, dict) else row[0]
            try:
                current = json.loads(raw) or {}
            except (TypeError, json.JSONDecodeError):
                current = {}

        new_state = mutator(current)
        payload = json.dumps(new_state, ensure_ascii=False)

        if _use_postgres():
            conn.execute(
                f"""INSERT INTO runtime_state(id, updated_at, state_json)
                    VALUES(1, {p}, {p})
                    ON CONFLICT (id) DO UPDATE SET
                        updated_at = EXCLUDED.updated_at,
                        state_json = EXCLUDED.state_json""",
                (utc_now(), payload),
            )
        else:
            conn.execute(
                f"""INSERT INTO runtime_state(id, updated_at, state_json)
                    VALUES(1, {p}, {p})
                    ON CONFLICT(id) DO UPDATE SET
                        updated_at=excluded.updated_at,
                        state_json=excluded.state_json""",
                (utc_now(), payload),
            )
        conn.commit()
        return new_state


def get_runtime_state():
    """Return the latest shared live state, or None if it has not been seeded."""
    init_db()
    with _connect() as conn:
        row = conn.execute("SELECT state_json FROM runtime_state WHERE id=1").fetchone()
    if not row:
        return None
    raw = row["state_json"] if isinstance(row, dict) else row[0]
    try:
        return json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        return None


def save_state(state):
    """Persist a point-in-time snapshot of the system state."""
    init_db()
    p = _placeholder()
    with _connect() as conn:
        conn.execute(
            f"INSERT INTO state_history(created_at,state_json) VALUES({p},{p})",
            (utc_now(), json.dumps(state, ensure_ascii=False)),
        )
        conn.commit()


def get_events(limit=100, event_type=None, severity=None):
    init_db()
    limit = max(1, min(int(limit), 1000))
    clauses, args = [], []
    p = _placeholder()
    if event_type:
        clauses.append(f"event_type = {p}")
        args.append(event_type)
    if severity:
        clauses.append(f"severity = {p}")
        args.append(severity)

    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    sql = f"""SELECT id,created_at,event_type,severity,source,location,
                       message,snapshot_path,metadata
                FROM events{where}
                ORDER BY id DESC LIMIT {p}"""
    args.append(limit)
    with _connect() as conn:
        rows = conn.execute(sql, tuple(args)).fetchall()
    return [dict(r) for r in rows]


def get_event(event_id):
    init_db()
    p = _placeholder()
    with _connect() as conn:
        row = conn.execute(
            f"SELECT * FROM events WHERE id = {p}", (event_id,)
        ).fetchone()
    return dict(row) if row else None


def get_stats():
    """Return History statistics using backend-independent named columns.

    PostgreSQL connections use psycopg's ``dict_row`` factory, so
    ``fetchone()`` returns a mapping rather than a positional tuple. SQLite
    uses ``sqlite3.Row`` here, which also supports named-column access. Using
    explicit aliases keeps this function correct on both backends.
    """
    init_db()
    with _connect() as conn:
        total = conn.execute(
            "SELECT COUNT(*) AS total FROM events"
        ).fetchone()["total"]
        critical = conn.execute(
            "SELECT COUNT(*) AS critical FROM events "
            "WHERE severity IN ('critical','danger')"
        ).fetchone()["critical"]
        warnings = conn.execute(
            "SELECT COUNT(*) AS warnings FROM events "
            "WHERE severity='warning'"
        ).fetchone()["warnings"]
        incidents = conn.execute(
            "SELECT COUNT(*) AS incidents FROM events "
            "WHERE event_type='security_breach'"
        ).fetchone()["incidents"]
    return {"total": total, "critical": critical, "warnings": warnings,
            "incidents": incidents}



def _retention_days(name, default):
    """Read a non-negative retention period from the environment."""
    raw = os.getenv(name, str(default)).strip()
    try:
        value = int(raw)
    except ValueError as exc:
        raise ValueError(f"{name} must be a whole number of days") from exc
    if value < 0:
        raise ValueError(f"{name} cannot be negative")
    return value


def get_retention_policy():
    """Return configurable history-retention periods in days.

    INFO/low-value events are retained for 30 days by default, warnings for
    90 days, and critical/danger events are retained indefinitely (0 means
    never automatically delete). State snapshots use the info retention.
    """
    return {
        "info_days": _retention_days("RETENTION_INFO_DAYS", 30),
        "warning_days": _retention_days("RETENTION_WARNING_DAYS", 90),
        "state_days": _retention_days("RETENTION_STATE_DAYS", 30),
    }


def cleanup_expired_records(now=None, info_days=None, warning_days=None, state_days=None):
    """Delete expired low-value history while preserving critical incidents.

    Severity policy:
    - ``critical`` and ``danger`` events are never automatically deleted.
    - ``warning`` events use the warning retention period.
    - all other events are treated as low-value/info events.
    - state snapshots use their own retention period.

    Returns a dictionary containing the number of deleted event and state
    records. ``now`` is injectable to make retention deterministic in tests.
    """
    policy = get_retention_policy()
    info_days = policy["info_days"] if info_days is None else max(0, int(info_days))
    warning_days = policy["warning_days"] if warning_days is None else max(0, int(warning_days))
    state_days = policy["state_days"] if state_days is None else max(0, int(state_days))

    current = now or datetime.now(timezone.utc)
    if current.tzinfo is None:
        current = current.replace(tzinfo=timezone.utc)

    def cutoff(days):
        return (current - timedelta(days=days)).isoformat(timespec="seconds")

    info_cutoff = cutoff(info_days)
    warning_cutoff = cutoff(warning_days)
    state_cutoff = cutoff(state_days)

    init_db()
    p = _placeholder()
    with _connect() as conn:
        # A zero-day retention is interpreted as immediate expiry for that
        # low-value class. Critical/danger records are explicitly excluded.
        event_sql = f"""
            DELETE FROM events
            WHERE (
                (severity = {p} AND created_at < {p})
                OR (
                    severity NOT IN ({p}, {p})
                    AND severity <> {p}
                    AND created_at < {p}
                )
            )
        """
        event_params = (
            "warning", warning_cutoff,
            "critical", "danger", "warning", info_cutoff,
        )
        cur = conn.execute(event_sql, event_params)
        events_deleted = cur.rowcount if cur.rowcount is not None and cur.rowcount >= 0 else 0

        state_cur = conn.execute(
            f"DELETE FROM state_history WHERE created_at < {p}",
            (state_cutoff,),
        )
        states_deleted = state_cur.rowcount if state_cur.rowcount is not None and state_cur.rowcount >= 0 else 0
        conn.commit()

    return {"events_deleted": events_deleted, "states_deleted": states_deleted}

def clear_history():
    init_db()
    with _connect() as conn:
        conn.execute("DELETE FROM events")
        conn.execute("DELETE FROM state_history")
        conn.commit()


def get_backend():
    """Return the active backend name for diagnostics and deployment checks."""
    return "postgresql" if _use_postgres() else "sqlite"


def migrate_sqlite_to_postgres(sqlite_path=None, postgres_url=None):
    """Copy existing SQLite history into a PostgreSQL/Neon database.

    This is an explicit migration utility; it never runs automatically during
    normal application startup. Existing IDs are preserved, and PostgreSQL
    identity sequences are advanced after the import.
    """
    if not postgres_url:
        postgres_url = _database_url()
    if not postgres_url or not postgres_url.startswith(("postgres://", "postgresql://")):
        raise ValueError("A valid PostgreSQL DATABASE_URL is required for migration.")

    source_path = Path(sqlite_path or DB_PATH)
    if not source_path.exists():
        raise FileNotFoundError(f"SQLite database not found: {source_path}")

    try:
        import psycopg
    except ImportError as exc:
        raise RuntimeError("Install psycopg[binary] before running the migration.") from exc

    source = sqlite3.connect(source_path)
    source.row_factory = sqlite3.Row
    target = psycopg.connect(postgres_url)
    try:
        # Schema creation is independent of DATABASE_URL so the migration can
        # target a URL different from the process environment.
        for statement in [
            """
            CREATE TABLE IF NOT EXISTS events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL,
                event_type TEXT NOT NULL,
                severity TEXT NOT NULL DEFAULT 'info',
                source TEXT NOT NULL,
                location TEXT,
                message TEXT NOT NULL,
                snapshot_path TEXT,
                metadata TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type)",
            "CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity)",
            """
            CREATE TABLE IF NOT EXISTS state_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL,
                state_json TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_events_retention ON events(severity, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_state_history_created_at ON state_history(created_at)",
        ]:
            target.execute(statement)

        events = source.execute("SELECT * FROM events ORDER BY id").fetchall()
        states = source.execute("SELECT * FROM state_history ORDER BY id").fetchall()

        for row in events:
            target.execute(
                """INSERT INTO events
                (id,created_at,event_type,severity,source,location,message,snapshot_path,metadata)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (id) DO NOTHING""",
                tuple(row),
            )

        for row in states:
            target.execute(
                """INSERT INTO state_history
                (id,created_at,state_json)
                VALUES (%s,%s,%s)
                ON CONFLICT (id) DO NOTHING""",
                tuple(row),
            )

        # Keep generated IDs above imported IDs.
        target.execute(
            """SELECT setval(
                pg_get_serial_sequence('events', 'id'),
                COALESCE((SELECT MAX(id) FROM events), 1),
                (SELECT COUNT(*) > 0 FROM events)
            )"""
        )
        target.execute(
            """SELECT setval(
                pg_get_serial_sequence('state_history', 'id'),
                COALESCE((SELECT MAX(id) FROM state_history), 1),
                (SELECT COUNT(*) > 0 FROM state_history)
            )"""
        )
        target.commit()
        return {"events": len(events), "states": len(states)}
    finally:
        source.close()
        target.close()


init_db()
